# Funding sources shown on the repository's "Sponsor" button.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [theBGuy]
# Uncomment and fill in any others you use:
# ko_fi: your_username
buy_me_a_coffee: theBGuy
# open_collective: your_project
# custom: ["https://example.com/donate"]
